# Generated by Django 6.0.4 on 2026-04-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.BigIntegerField()),
                ('receiver_id', models.BigIntegerField()),
                ('job_id', models.BigIntegerField()),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['job_id'], name='messages_job_id_6c0007_idx'), models.Index(fields=['receiver_id', 'is_read'], name='messages_receive_c45f39_idx'), models.Index(fields=['sender_id', 'receiver_id'], name='messages_sender__89e028_idx')],
            },
        ),
    ]
